version: '3.9'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - client
      - api
    networks:
      - frontend

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - frontend

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api
    volumes:
      - ./api:/app
      - /app/node_modules
    depends_on:
      - mysql
      - osrm-backend
    networks:
      - frontend
      - backend
    command: ["npm", "run", "dev"]

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: desirelessDB
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - backend
    ports:
      - "3306:3306" 


  osrm-backend:
    image: osrm/osrm-backend
    container_name: osrm-backend
    volumes:
      - ./osrm/data:/data
    expose:
      - "5000"
    command: >
      osrm-routed --algorithm mld /data/rhone-alpes-latest.osrm
    networks:
      - backend


  osrm-backend:
    image: osrm/osrm-backend
    container_name: osrm-backend
    volumes:
      - ./osrm/data:/data
    expose:
      - "5000"
    command: >
      osrm-routed --algorithm mld /data/rhone-alpes-latest.osrm
    networks:
      - backend

volumes:
  mysql-data:

  
networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
