version: '3.9'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api

  api:
    build: ./api
    ports:
      - "3000:3000"
    volumes:
      - ./api:/usr/src
    working_dir: /usr/src/app
    command: npm start
    depends_on:
      - mysql

  client:
    build: ./client
    ports:
      - "3001:3000"
    volumes:
      - ./client:/usr/src/app
    working_dir: /usr/src/app
    command: npm run dev

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: desirelessDB
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
  
