version: '3.9'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - client
      - api
    networks:
      - frontend

  client:
    build: ./client
    container_name: client
    #ports:
    #  - "4000:4000"
    volumes:
      - ./client:/usr/src
    working_dir: /usr/src/app
    command: npm run dev -- --host
    networks:
      - frontend

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api
    #ports:
    #  - "3000:3000"
    volumes:
      - ./api:/usr/src
    # working_dir: /usr/src/app
    depends_on:
      - mysql
    networks:
      - frontend
      - backend

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: desirelessDB
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - backend

volumes:
  mysql-data:
  
networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
